apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - variables.yaml
  - ../base

namespace: team-a-jenkins
patchesStrategicMerge:
  - release.yaml

#namePrefix: team-a-
