---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: project-a
  name: project-a

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: project-a
  name: project-a
  namespace: project-a

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: project-a
  name: gotk-reconciler
  namespace: project-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: gotk:project-a:reconciler
  #name: gotk:apps:reconciler  
- kind: ServiceAccount
  name: project-a
  namespace: project-a
