---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:
  values:
    controller:
      image: "jenkins/jenkins"
      jenkinsUriPrefix: /team-a-jenkins
      JCasC:
        defaultConfig: true
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: Welcome from team-a.
