---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: "./apps/kind-dev/team-a-jenkins"
  postBuild:
    substitute:
      SEED_JOB: "team-a.git"

