---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  validation: client
  path: "./apps/kind-dev/team-b-jenkins"
  postBuild:
    substitute:
      cicd_repo_url: "git@github.com:dev-samples/team-b.git"

